# CMake generated Testfile for 
# Source directory: C:/Workspace/audacity/libraries/lib-string-utils/tests
# Build directory: C:/Workspace/audacity/visual_studio/libraries/lib-string-utils/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(lib-string-utils "C:/Workspace/audacity/visual_studio/tests/Debug/lib-string-utils-test.exe")
  set_tests_properties(lib-string-utils PROPERTIES  ENVIRONMENT "PATH=C:\\Workspace\\audacity\\visual_studio\\Debug\\;C:\\Users\\giaco\\bin\\;C:\\Program Files\\Git\\mingw64\\bin\\;C:\\Program Files\\Git\\usr\\local\\bin\\;C:\\Program Files\\Git\\usr\\bin\\;C:\\Program Files\\Git\\usr\\bin\\;C:\\Program Files\\Git\\mingw64\\bin\\;C:\\Program Files\\Git\\usr\\bin\\;C:\\Users\\giaco\\bin\\;C:\\Windows\\system32\\;C:\\Windows\\;C:\\Windows\\System32\\Wbem\\;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common\\;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR\\;C:\\WINDOWS\\system32\\;C:\\WINDOWS\\;C:\\WINDOWS\\System32\\Wbem\\;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\Git\\cmd\\;C:\\Program Files\\CMake\\bin\\;C:\\Workspace\\obs-build-dependencies\\windows-deps-2023-01-06-x64\\;C:\\Program Files\\TortoiseHg\\;C:\\Users\\giaco\\AppData\\Local\\Programs\\Python\\Python311\\;C:\\Users\\giaco\\AppData\\Local\\Programs\\Python\\Python311\\Scripts\\;C:\\Users\\giaco\\AppData\\Local\\Microsoft\\WindowsApps\\;C:\\Program Files\\Git\\usr\\bin\\vendor_perl\\;C:\\Program Files\\Git\\usr\\bin\\core_perl" LABELS "unit_tests" _BACKTRACE_TRIPLES "C:/Workspace/audacity/cmake-proxies/cmake-modules/AudacityTesting.cmake;55;add_test;C:/Workspace/audacity/libraries/lib-string-utils/tests/CMakeLists.txt;1;add_unit_test;C:/Workspace/audacity/libraries/lib-string-utils/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(lib-string-utils "C:/Workspace/audacity/visual_studio/tests/Release/lib-string-utils-test.exe")
  set_tests_properties(lib-string-utils PROPERTIES  ENVIRONMENT "PATH=C:\\Workspace\\audacity\\visual_studio\\Release\\;C:\\Users\\giaco\\bin\\;C:\\Program Files\\Git\\mingw64\\bin\\;C:\\Program Files\\Git\\usr\\local\\bin\\;C:\\Program Files\\Git\\usr\\bin\\;C:\\Program Files\\Git\\usr\\bin\\;C:\\Program Files\\Git\\mingw64\\bin\\;C:\\Program Files\\Git\\usr\\bin\\;C:\\Users\\giaco\\bin\\;C:\\Windows\\system32\\;C:\\Windows\\;C:\\Windows\\System32\\Wbem\\;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common\\;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR\\;C:\\WINDOWS\\system32\\;C:\\WINDOWS\\;C:\\WINDOWS\\System32\\Wbem\\;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\Git\\cmd\\;C:\\Program Files\\CMake\\bin\\;C:\\Workspace\\obs-build-dependencies\\windows-deps-2023-01-06-x64\\;C:\\Program Files\\TortoiseHg\\;C:\\Users\\giaco\\AppData\\Local\\Programs\\Python\\Python311\\;C:\\Users\\giaco\\AppData\\Local\\Programs\\Python\\Python311\\Scripts\\;C:\\Users\\giaco\\AppData\\Local\\Microsoft\\WindowsApps\\;C:\\Program Files\\Git\\usr\\bin\\vendor_perl\\;C:\\Program Files\\Git\\usr\\bin\\core_perl" LABELS "unit_tests" _BACKTRACE_TRIPLES "C:/Workspace/audacity/cmake-proxies/cmake-modules/AudacityTesting.cmake;55;add_test;C:/Workspace/audacity/libraries/lib-string-utils/tests/CMakeLists.txt;1;add_unit_test;C:/Workspace/audacity/libraries/lib-string-utils/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(lib-string-utils "C:/Workspace/audacity/visual_studio/tests/MinSizeRel/lib-string-utils-test.exe")
  set_tests_properties(lib-string-utils PROPERTIES  ENVIRONMENT "PATH=C:\\Workspace\\audacity\\visual_studio\\MinSizeRel\\;C:\\Users\\giaco\\bin\\;C:\\Program Files\\Git\\mingw64\\bin\\;C:\\Program Files\\Git\\usr\\local\\bin\\;C:\\Program Files\\Git\\usr\\bin\\;C:\\Program Files\\Git\\usr\\bin\\;C:\\Program Files\\Git\\mingw64\\bin\\;C:\\Program Files\\Git\\usr\\bin\\;C:\\Users\\giaco\\bin\\;C:\\Windows\\system32\\;C:\\Windows\\;C:\\Windows\\System32\\Wbem\\;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common\\;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR\\;C:\\WINDOWS\\system32\\;C:\\WINDOWS\\;C:\\WINDOWS\\System32\\Wbem\\;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\Git\\cmd\\;C:\\Program Files\\CMake\\bin\\;C:\\Workspace\\obs-build-dependencies\\windows-deps-2023-01-06-x64\\;C:\\Program Files\\TortoiseHg\\;C:\\Users\\giaco\\AppData\\Local\\Programs\\Python\\Python311\\;C:\\Users\\giaco\\AppData\\Local\\Programs\\Python\\Python311\\Scripts\\;C:\\Users\\giaco\\AppData\\Local\\Microsoft\\WindowsApps\\;C:\\Program Files\\Git\\usr\\bin\\vendor_perl\\;C:\\Program Files\\Git\\usr\\bin\\core_perl" LABELS "unit_tests" _BACKTRACE_TRIPLES "C:/Workspace/audacity/cmake-proxies/cmake-modules/AudacityTesting.cmake;55;add_test;C:/Workspace/audacity/libraries/lib-string-utils/tests/CMakeLists.txt;1;add_unit_test;C:/Workspace/audacity/libraries/lib-string-utils/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(lib-string-utils "C:/Workspace/audacity/visual_studio/tests/RelWithDebInfo/lib-string-utils-test.exe")
  set_tests_properties(lib-string-utils PROPERTIES  ENVIRONMENT "PATH=C:\\Workspace\\audacity\\visual_studio\\RelWithDebInfo\\;C:\\Users\\giaco\\bin\\;C:\\Program Files\\Git\\mingw64\\bin\\;C:\\Program Files\\Git\\usr\\local\\bin\\;C:\\Program Files\\Git\\usr\\bin\\;C:\\Program Files\\Git\\usr\\bin\\;C:\\Program Files\\Git\\mingw64\\bin\\;C:\\Program Files\\Git\\usr\\bin\\;C:\\Users\\giaco\\bin\\;C:\\Windows\\system32\\;C:\\Windows\\;C:\\Windows\\System32\\Wbem\\;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common\\;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR\\;C:\\WINDOWS\\system32\\;C:\\WINDOWS\\;C:\\WINDOWS\\System32\\Wbem\\;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\Git\\cmd\\;C:\\Program Files\\CMake\\bin\\;C:\\Workspace\\obs-build-dependencies\\windows-deps-2023-01-06-x64\\;C:\\Program Files\\TortoiseHg\\;C:\\Users\\giaco\\AppData\\Local\\Programs\\Python\\Python311\\;C:\\Users\\giaco\\AppData\\Local\\Programs\\Python\\Python311\\Scripts\\;C:\\Users\\giaco\\AppData\\Local\\Microsoft\\WindowsApps\\;C:\\Program Files\\Git\\usr\\bin\\vendor_perl\\;C:\\Program Files\\Git\\usr\\bin\\core_perl" LABELS "unit_tests" _BACKTRACE_TRIPLES "C:/Workspace/audacity/cmake-proxies/cmake-modules/AudacityTesting.cmake;55;add_test;C:/Workspace/audacity/libraries/lib-string-utils/tests/CMakeLists.txt;1;add_unit_test;C:/Workspace/audacity/libraries/lib-string-utils/tests/CMakeLists.txt;0;")
else()
  add_test(lib-string-utils NOT_AVAILABLE)
endif()
