# Generated dependecies list
find_package( ZLIB REQUIRED )
find_package( EXPAT REQUIRED )
find_package( PNG QUIET )
find_package( JPEG QUIET )
find_package( wxWidgets REQUIRED COMPONENTS adv base core html qa xml net )
find_package( libmp3lame REQUIRED )
find_package( mpg123 )
find_package( libid3tag )
find_package( WavPack )
find_package( Ogg )
find_package( FLAC )
find_package( Opus )
find_package( Vorbis )
find_package( SndFile )
find_package( PortAudio REQUIRED )
find_package( PortMidi )
find_package( vst3sdk REQUIRED )
find_package( Catch2 REQUIRED )
