########### AGGREGATED COMPONENTS AND DEPENDENCIES FOR THE MULTI CONFIG #####################
#############################################################################################

set(expat_COMPONENT_NAMES "")
set(expat_FIND_DEPENDENCY_NAMES "")

########### VARIABLES #######################################################################
#############################################################################################
set(expat_PACKAGE_FOLDER_RELWITHDEBINFO "C:/Users/giaco/.conan/data/expat/2.2.9/audacity/stable/package/ad5261bf6074807e7189c351b0f79b113bf2f6c0")
set(expat_BUILD_MODULES_PATHS_RELWITHDEBINFO )


set(expat_INCLUDE_DIRS_RELWITHDEBINFO "${expat_PACKAGE_FOLDER_RELWITHDEBINFO}/include")
set(expat_RES_DIRS_RELWITHDEBINFO "${expat_PACKAGE_FOLDER_RELWITHDEBINFO}/res")
set(expat_DEFINITIONS_RELWITHDEBINFO )
set(expat_SHARED_LINK_FLAGS_RELWITHDEBINFO )
set(expat_EXE_LINK_FLAGS_RELWITHDEBINFO )
set(expat_OBJECTS_RELWITHDEBINFO )
set(expat_COMPILE_DEFINITIONS_RELWITHDEBINFO )
set(expat_COMPILE_OPTIONS_C_RELWITHDEBINFO )
set(expat_COMPILE_OPTIONS_CXX_RELWITHDEBINFO )
set(expat_LIB_DIRS_RELWITHDEBINFO "${expat_PACKAGE_FOLDER_RELWITHDEBINFO}/lib")
set(expat_LIBS_RELWITHDEBINFO libexpat)
set(expat_SYSTEM_LIBS_RELWITHDEBINFO )
set(expat_FRAMEWORK_DIRS_RELWITHDEBINFO "${expat_PACKAGE_FOLDER_RELWITHDEBINFO}/Frameworks")
set(expat_FRAMEWORKS_RELWITHDEBINFO )
set(expat_BUILD_DIRS_RELWITHDEBINFO "${expat_PACKAGE_FOLDER_RELWITHDEBINFO}/")

# COMPOUND VARIABLES
set(expat_COMPILE_OPTIONS_RELWITHDEBINFO
    "$<$<COMPILE_LANGUAGE:CXX>:${expat_COMPILE_OPTIONS_CXX_RELWITHDEBINFO}>"
    "$<$<COMPILE_LANGUAGE:C>:${expat_COMPILE_OPTIONS_C_RELWITHDEBINFO}>")
set(expat_LINKER_FLAGS_RELWITHDEBINFO
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:${expat_SHARED_LINK_FLAGS_RELWITHDEBINFO}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:${expat_SHARED_LINK_FLAGS_RELWITHDEBINFO}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:${expat_EXE_LINK_FLAGS_RELWITHDEBINFO}>")


set(expat_COMPONENTS_RELWITHDEBINFO )