########### AGGREGATED COMPONENTS AND DEPENDENCIES FOR THE MULTI CONFIG #####################
#############################################################################################

list(APPEND flac_COMPONENT_NAMES FLAC::FLAC FLAC::FLAC++)
list(REMOVE_DUPLICATES flac_COMPONENT_NAMES)
list(APPEND flac_FIND_DEPENDENCY_NAMES Ogg)
list(REMOVE_DUPLICATES flac_FIND_DEPENDENCY_NAMES)
set(Ogg_FIND_MODE "NO_MODULE")

########### VARIABLES #######################################################################
#############################################################################################
set(flac_PACKAGE_FOLDER_RELWITHDEBINFO "C:/Users/giaco/.conan/data/flac/1.3.3/_/_/package/3b26581a680ab99eb0ef725aa935a0289708df91")
set(flac_BUILD_MODULES_PATHS_RELWITHDEBINFO )


set(flac_INCLUDE_DIRS_RELWITHDEBINFO "${flac_PACKAGE_FOLDER_RELWITHDEBINFO}/include")
set(flac_RES_DIRS_RELWITHDEBINFO )
set(flac_DEFINITIONS_RELWITHDEBINFO )
set(flac_SHARED_LINK_FLAGS_RELWITHDEBINFO )
set(flac_EXE_LINK_FLAGS_RELWITHDEBINFO )
set(flac_OBJECTS_RELWITHDEBINFO )
set(flac_COMPILE_DEFINITIONS_RELWITHDEBINFO )
set(flac_COMPILE_OPTIONS_C_RELWITHDEBINFO )
set(flac_COMPILE_OPTIONS_CXX_RELWITHDEBINFO )
set(flac_LIB_DIRS_RELWITHDEBINFO "${flac_PACKAGE_FOLDER_RELWITHDEBINFO}/lib")
set(flac_LIBS_RELWITHDEBINFO FLAC++ FLAC)
set(flac_SYSTEM_LIBS_RELWITHDEBINFO )
set(flac_FRAMEWORK_DIRS_RELWITHDEBINFO )
set(flac_FRAMEWORKS_RELWITHDEBINFO )
set(flac_BUILD_DIRS_RELWITHDEBINFO )

# COMPOUND VARIABLES
set(flac_COMPILE_OPTIONS_RELWITHDEBINFO
    "$<$<COMPILE_LANGUAGE:CXX>:${flac_COMPILE_OPTIONS_CXX_RELWITHDEBINFO}>"
    "$<$<COMPILE_LANGUAGE:C>:${flac_COMPILE_OPTIONS_C_RELWITHDEBINFO}>")
set(flac_LINKER_FLAGS_RELWITHDEBINFO
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:${flac_SHARED_LINK_FLAGS_RELWITHDEBINFO}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:${flac_SHARED_LINK_FLAGS_RELWITHDEBINFO}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:${flac_EXE_LINK_FLAGS_RELWITHDEBINFO}>")


set(flac_COMPONENTS_RELWITHDEBINFO FLAC::FLAC FLAC::FLAC++)
########### COMPONENT FLAC::FLAC++ VARIABLES ############################################

set(flac_FLAC_FLAC++_INCLUDE_DIRS_RELWITHDEBINFO "${flac_PACKAGE_FOLDER_RELWITHDEBINFO}/include")
set(flac_FLAC_FLAC++_LIB_DIRS_RELWITHDEBINFO "${flac_PACKAGE_FOLDER_RELWITHDEBINFO}/lib")
set(flac_FLAC_FLAC++_RES_DIRS_RELWITHDEBINFO )
set(flac_FLAC_FLAC++_DEFINITIONS_RELWITHDEBINFO )
set(flac_FLAC_FLAC++_OBJECTS_RELWITHDEBINFO )
set(flac_FLAC_FLAC++_COMPILE_DEFINITIONS_RELWITHDEBINFO )
set(flac_FLAC_FLAC++_COMPILE_OPTIONS_C_RELWITHDEBINFO "")
set(flac_FLAC_FLAC++_COMPILE_OPTIONS_CXX_RELWITHDEBINFO "")
set(flac_FLAC_FLAC++_LIBS_RELWITHDEBINFO FLAC++)
set(flac_FLAC_FLAC++_SYSTEM_LIBS_RELWITHDEBINFO )
set(flac_FLAC_FLAC++_FRAMEWORK_DIRS_RELWITHDEBINFO )
set(flac_FLAC_FLAC++_FRAMEWORKS_RELWITHDEBINFO )
set(flac_FLAC_FLAC++_DEPENDENCIES_RELWITHDEBINFO FLAC::FLAC)
set(flac_FLAC_FLAC++_SHARED_LINK_FLAGS_RELWITHDEBINFO )
set(flac_FLAC_FLAC++_EXE_LINK_FLAGS_RELWITHDEBINFO )
# COMPOUND VARIABLES
set(flac_FLAC_FLAC++_LINKER_FLAGS_RELWITHDEBINFO
        $<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:${flac_FLAC_FLAC++_SHARED_LINK_FLAGS_RELWITHDEBINFO}>
        $<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:${flac_FLAC_FLAC++_SHARED_LINK_FLAGS_RELWITHDEBINFO}>
        $<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:${flac_FLAC_FLAC++_EXE_LINK_FLAGS_RELWITHDEBINFO}>
)
set(flac_FLAC_FLAC++_COMPILE_OPTIONS_RELWITHDEBINFO
    "$<$<COMPILE_LANGUAGE:CXX>:${flac_FLAC_FLAC++_COMPILE_OPTIONS_CXX_RELWITHDEBINFO}>"
    "$<$<COMPILE_LANGUAGE:C>:${flac_FLAC_FLAC++_COMPILE_OPTIONS_C_RELWITHDEBINFO}>")
########### COMPONENT FLAC::FLAC VARIABLES ############################################

set(flac_FLAC_FLAC_INCLUDE_DIRS_RELWITHDEBINFO "${flac_PACKAGE_FOLDER_RELWITHDEBINFO}/include")
set(flac_FLAC_FLAC_LIB_DIRS_RELWITHDEBINFO "${flac_PACKAGE_FOLDER_RELWITHDEBINFO}/lib")
set(flac_FLAC_FLAC_RES_DIRS_RELWITHDEBINFO )
set(flac_FLAC_FLAC_DEFINITIONS_RELWITHDEBINFO )
set(flac_FLAC_FLAC_OBJECTS_RELWITHDEBINFO )
set(flac_FLAC_FLAC_COMPILE_DEFINITIONS_RELWITHDEBINFO )
set(flac_FLAC_FLAC_COMPILE_OPTIONS_C_RELWITHDEBINFO "")
set(flac_FLAC_FLAC_COMPILE_OPTIONS_CXX_RELWITHDEBINFO "")
set(flac_FLAC_FLAC_LIBS_RELWITHDEBINFO FLAC)
set(flac_FLAC_FLAC_SYSTEM_LIBS_RELWITHDEBINFO )
set(flac_FLAC_FLAC_FRAMEWORK_DIRS_RELWITHDEBINFO )
set(flac_FLAC_FLAC_FRAMEWORKS_RELWITHDEBINFO )
set(flac_FLAC_FLAC_DEPENDENCIES_RELWITHDEBINFO Ogg::ogg)
set(flac_FLAC_FLAC_SHARED_LINK_FLAGS_RELWITHDEBINFO )
set(flac_FLAC_FLAC_EXE_LINK_FLAGS_RELWITHDEBINFO )
# COMPOUND VARIABLES
set(flac_FLAC_FLAC_LINKER_FLAGS_RELWITHDEBINFO
        $<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:${flac_FLAC_FLAC_SHARED_LINK_FLAGS_RELWITHDEBINFO}>
        $<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:${flac_FLAC_FLAC_SHARED_LINK_FLAGS_RELWITHDEBINFO}>
        $<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:${flac_FLAC_FLAC_EXE_LINK_FLAGS_RELWITHDEBINFO}>
)
set(flac_FLAC_FLAC_COMPILE_OPTIONS_RELWITHDEBINFO
    "$<$<COMPILE_LANGUAGE:CXX>:${flac_FLAC_FLAC_COMPILE_OPTIONS_CXX_RELWITHDEBINFO}>"
    "$<$<COMPILE_LANGUAGE:C>:${flac_FLAC_FLAC_COMPILE_OPTIONS_C_RELWITHDEBINFO}>")