########### AGGREGATED COMPONENTS AND DEPENDENCIES FOR THE MULTI CONFIG #####################
#############################################################################################

list(APPEND ogg_COMPONENT_NAMES Ogg::ogg)
list(REMOVE_DUPLICATES ogg_COMPONENT_NAMES)
set(ogg_FIND_DEPENDENCY_NAMES "")

########### VARIABLES #######################################################################
#############################################################################################
set(ogg_PACKAGE_FOLDER_MINSIZEREL "C:/Users/giaco/.conan/data/ogg/1.3.4/_/_/package/ad5261bf6074807e7189c351b0f79b113bf2f6c0")
set(ogg_BUILD_MODULES_PATHS_MINSIZEREL )


set(ogg_INCLUDE_DIRS_MINSIZEREL "${ogg_PACKAGE_FOLDER_MINSIZEREL}/include")
set(ogg_RES_DIRS_MINSIZEREL )
set(ogg_DEFINITIONS_MINSIZEREL )
set(ogg_SHARED_LINK_FLAGS_MINSIZEREL )
set(ogg_EXE_LINK_FLAGS_MINSIZEREL )
set(ogg_OBJECTS_MINSIZEREL )
set(ogg_COMPILE_DEFINITIONS_MINSIZEREL )
set(ogg_COMPILE_OPTIONS_C_MINSIZEREL )
set(ogg_COMPILE_OPTIONS_CXX_MINSIZEREL )
set(ogg_LIB_DIRS_MINSIZEREL "${ogg_PACKAGE_FOLDER_MINSIZEREL}/lib")
set(ogg_LIBS_MINSIZEREL ogg)
set(ogg_SYSTEM_LIBS_MINSIZEREL )
set(ogg_FRAMEWORK_DIRS_MINSIZEREL )
set(ogg_FRAMEWORKS_MINSIZEREL )
set(ogg_BUILD_DIRS_MINSIZEREL )

# COMPOUND VARIABLES
set(ogg_COMPILE_OPTIONS_MINSIZEREL
    "$<$<COMPILE_LANGUAGE:CXX>:${ogg_COMPILE_OPTIONS_CXX_MINSIZEREL}>"
    "$<$<COMPILE_LANGUAGE:C>:${ogg_COMPILE_OPTIONS_C_MINSIZEREL}>")
set(ogg_LINKER_FLAGS_MINSIZEREL
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:${ogg_SHARED_LINK_FLAGS_MINSIZEREL}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:${ogg_SHARED_LINK_FLAGS_MINSIZEREL}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:${ogg_EXE_LINK_FLAGS_MINSIZEREL}>")


set(ogg_COMPONENTS_MINSIZEREL Ogg::ogg)
########### COMPONENT Ogg::ogg VARIABLES ############################################

set(ogg_Ogg_ogg_INCLUDE_DIRS_MINSIZEREL "${ogg_PACKAGE_FOLDER_MINSIZEREL}/include")
set(ogg_Ogg_ogg_LIB_DIRS_MINSIZEREL "${ogg_PACKAGE_FOLDER_MINSIZEREL}/lib")
set(ogg_Ogg_ogg_RES_DIRS_MINSIZEREL )
set(ogg_Ogg_ogg_DEFINITIONS_MINSIZEREL )
set(ogg_Ogg_ogg_OBJECTS_MINSIZEREL )
set(ogg_Ogg_ogg_COMPILE_DEFINITIONS_MINSIZEREL )
set(ogg_Ogg_ogg_COMPILE_OPTIONS_C_MINSIZEREL "")
set(ogg_Ogg_ogg_COMPILE_OPTIONS_CXX_MINSIZEREL "")
set(ogg_Ogg_ogg_LIBS_MINSIZEREL ogg)
set(ogg_Ogg_ogg_SYSTEM_LIBS_MINSIZEREL )
set(ogg_Ogg_ogg_FRAMEWORK_DIRS_MINSIZEREL )
set(ogg_Ogg_ogg_FRAMEWORKS_MINSIZEREL )
set(ogg_Ogg_ogg_DEPENDENCIES_MINSIZEREL )
set(ogg_Ogg_ogg_SHARED_LINK_FLAGS_MINSIZEREL )
set(ogg_Ogg_ogg_EXE_LINK_FLAGS_MINSIZEREL )
# COMPOUND VARIABLES
set(ogg_Ogg_ogg_LINKER_FLAGS_MINSIZEREL
        $<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:${ogg_Ogg_ogg_SHARED_LINK_FLAGS_MINSIZEREL}>
        $<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:${ogg_Ogg_ogg_SHARED_LINK_FLAGS_MINSIZEREL}>
        $<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:${ogg_Ogg_ogg_EXE_LINK_FLAGS_MINSIZEREL}>
)
set(ogg_Ogg_ogg_COMPILE_OPTIONS_MINSIZEREL
    "$<$<COMPILE_LANGUAGE:CXX>:${ogg_Ogg_ogg_COMPILE_OPTIONS_CXX_MINSIZEREL}>"
    "$<$<COMPILE_LANGUAGE:C>:${ogg_Ogg_ogg_COMPILE_OPTIONS_C_MINSIZEREL}>")