########### AGGREGATED COMPONENTS AND DEPENDENCIES FOR THE MULTI CONFIG #####################
#############################################################################################

set(libpng_COMPONENT_NAMES "")
list(APPEND libpng_FIND_DEPENDENCY_NAMES ZLIB)
list(REMOVE_DUPLICATES libpng_FIND_DEPENDENCY_NAMES)
set(ZLIB_FIND_MODE "NO_MODULE")

########### VARIABLES #######################################################################
#############################################################################################
set(libpng_PACKAGE_FOLDER_RELWITHDEBINFO "C:/Users/giaco/.conan/data/libpng/1.6.37/_/_/package/c6d8367cbf7c047a38c0929c00d8d160cb8378db")
set(libpng_BUILD_MODULES_PATHS_RELWITHDEBINFO )


set(libpng_INCLUDE_DIRS_RELWITHDEBINFO "${libpng_PACKAGE_FOLDER_RELWITHDEBINFO}/include")
set(libpng_RES_DIRS_RELWITHDEBINFO )
set(libpng_DEFINITIONS_RELWITHDEBINFO )
set(libpng_SHARED_LINK_FLAGS_RELWITHDEBINFO )
set(libpng_EXE_LINK_FLAGS_RELWITHDEBINFO )
set(libpng_OBJECTS_RELWITHDEBINFO )
set(libpng_COMPILE_DEFINITIONS_RELWITHDEBINFO )
set(libpng_COMPILE_OPTIONS_C_RELWITHDEBINFO )
set(libpng_COMPILE_OPTIONS_CXX_RELWITHDEBINFO )
set(libpng_LIB_DIRS_RELWITHDEBINFO "${libpng_PACKAGE_FOLDER_RELWITHDEBINFO}/lib")
set(libpng_LIBS_RELWITHDEBINFO libpng16)
set(libpng_SYSTEM_LIBS_RELWITHDEBINFO )
set(libpng_FRAMEWORK_DIRS_RELWITHDEBINFO )
set(libpng_FRAMEWORKS_RELWITHDEBINFO )
set(libpng_BUILD_DIRS_RELWITHDEBINFO "${libpng_PACKAGE_FOLDER_RELWITHDEBINFO}/")

# COMPOUND VARIABLES
set(libpng_COMPILE_OPTIONS_RELWITHDEBINFO
    "$<$<COMPILE_LANGUAGE:CXX>:${libpng_COMPILE_OPTIONS_CXX_RELWITHDEBINFO}>"
    "$<$<COMPILE_LANGUAGE:C>:${libpng_COMPILE_OPTIONS_C_RELWITHDEBINFO}>")
set(libpng_LINKER_FLAGS_RELWITHDEBINFO
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:${libpng_SHARED_LINK_FLAGS_RELWITHDEBINFO}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:${libpng_SHARED_LINK_FLAGS_RELWITHDEBINFO}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:${libpng_EXE_LINK_FLAGS_RELWITHDEBINFO}>")


set(libpng_COMPONENTS_RELWITHDEBINFO )