########### AGGREGATED COMPONENTS AND DEPENDENCIES FOR THE MULTI CONFIG #####################
#############################################################################################

set(portmidi_COMPONENT_NAMES "")
set(portmidi_FIND_DEPENDENCY_NAMES "")

########### VARIABLES #######################################################################
#############################################################################################
set(portmidi_PACKAGE_FOLDER_RELWITHDEBINFO "C:/Users/giaco/.conan/data/portmidi/r234/_/_/package/ad5261bf6074807e7189c351b0f79b113bf2f6c0")
set(portmidi_BUILD_MODULES_PATHS_RELWITHDEBINFO )


set(portmidi_INCLUDE_DIRS_RELWITHDEBINFO "${portmidi_PACKAGE_FOLDER_RELWITHDEBINFO}/include")
set(portmidi_RES_DIRS_RELWITHDEBINFO "${portmidi_PACKAGE_FOLDER_RELWITHDEBINFO}/res")
set(portmidi_DEFINITIONS_RELWITHDEBINFO )
set(portmidi_SHARED_LINK_FLAGS_RELWITHDEBINFO )
set(portmidi_EXE_LINK_FLAGS_RELWITHDEBINFO )
set(portmidi_OBJECTS_RELWITHDEBINFO )
set(portmidi_COMPILE_DEFINITIONS_RELWITHDEBINFO )
set(portmidi_COMPILE_OPTIONS_C_RELWITHDEBINFO )
set(portmidi_COMPILE_OPTIONS_CXX_RELWITHDEBINFO )
set(portmidi_LIB_DIRS_RELWITHDEBINFO "${portmidi_PACKAGE_FOLDER_RELWITHDEBINFO}/lib")
set(portmidi_LIBS_RELWITHDEBINFO portmidi)
set(portmidi_SYSTEM_LIBS_RELWITHDEBINFO )
set(portmidi_FRAMEWORK_DIRS_RELWITHDEBINFO "${portmidi_PACKAGE_FOLDER_RELWITHDEBINFO}/Frameworks")
set(portmidi_FRAMEWORKS_RELWITHDEBINFO )
set(portmidi_BUILD_DIRS_RELWITHDEBINFO "${portmidi_PACKAGE_FOLDER_RELWITHDEBINFO}/")

# COMPOUND VARIABLES
set(portmidi_COMPILE_OPTIONS_RELWITHDEBINFO
    "$<$<COMPILE_LANGUAGE:CXX>:${portmidi_COMPILE_OPTIONS_CXX_RELWITHDEBINFO}>"
    "$<$<COMPILE_LANGUAGE:C>:${portmidi_COMPILE_OPTIONS_C_RELWITHDEBINFO}>")
set(portmidi_LINKER_FLAGS_RELWITHDEBINFO
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:${portmidi_SHARED_LINK_FLAGS_RELWITHDEBINFO}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:${portmidi_SHARED_LINK_FLAGS_RELWITHDEBINFO}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:${portmidi_EXE_LINK_FLAGS_RELWITHDEBINFO}>")


set(portmidi_COMPONENTS_RELWITHDEBINFO )