########### AGGREGATED COMPONENTS AND DEPENDENCIES FOR THE MULTI CONFIG #####################
#############################################################################################

set(zlib_COMPONENT_NAMES "")
set(zlib_FIND_DEPENDENCY_NAMES "")

########### VARIABLES #######################################################################
#############################################################################################
set(zlib_PACKAGE_FOLDER_RELWITHDEBINFO "C:/Users/giaco/.conan/data/zlib/1.2.11/_/_/package/ad5261bf6074807e7189c351b0f79b113bf2f6c0")
set(zlib_BUILD_MODULES_PATHS_RELWITHDEBINFO )


set(zlib_INCLUDE_DIRS_RELWITHDEBINFO "${zlib_PACKAGE_FOLDER_RELWITHDEBINFO}/include")
set(zlib_RES_DIRS_RELWITHDEBINFO )
set(zlib_DEFINITIONS_RELWITHDEBINFO )
set(zlib_SHARED_LINK_FLAGS_RELWITHDEBINFO )
set(zlib_EXE_LINK_FLAGS_RELWITHDEBINFO )
set(zlib_OBJECTS_RELWITHDEBINFO )
set(zlib_COMPILE_DEFINITIONS_RELWITHDEBINFO )
set(zlib_COMPILE_OPTIONS_C_RELWITHDEBINFO )
set(zlib_COMPILE_OPTIONS_CXX_RELWITHDEBINFO )
set(zlib_LIB_DIRS_RELWITHDEBINFO "${zlib_PACKAGE_FOLDER_RELWITHDEBINFO}/lib")
set(zlib_LIBS_RELWITHDEBINFO zdll)
set(zlib_SYSTEM_LIBS_RELWITHDEBINFO )
set(zlib_FRAMEWORK_DIRS_RELWITHDEBINFO )
set(zlib_FRAMEWORKS_RELWITHDEBINFO )
set(zlib_BUILD_DIRS_RELWITHDEBINFO "${zlib_PACKAGE_FOLDER_RELWITHDEBINFO}/")

# COMPOUND VARIABLES
set(zlib_COMPILE_OPTIONS_RELWITHDEBINFO
    "$<$<COMPILE_LANGUAGE:CXX>:${zlib_COMPILE_OPTIONS_CXX_RELWITHDEBINFO}>"
    "$<$<COMPILE_LANGUAGE:C>:${zlib_COMPILE_OPTIONS_C_RELWITHDEBINFO}>")
set(zlib_LINKER_FLAGS_RELWITHDEBINFO
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:${zlib_SHARED_LINK_FLAGS_RELWITHDEBINFO}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:${zlib_SHARED_LINK_FLAGS_RELWITHDEBINFO}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:${zlib_EXE_LINK_FLAGS_RELWITHDEBINFO}>")


set(zlib_COMPONENTS_RELWITHDEBINFO )