# CMake generated Testfile for 
# Source directory: C:/Workspace/audacity/libraries
# Build directory: C:/Workspace/audacity/visual_studio/libraries
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
subdirs("lib-string-utils")
subdirs("lib-strings")
subdirs("lib-utility")
subdirs("lib-uuid")
subdirs("lib-components")
subdirs("lib-basic-ui")
subdirs("lib-exceptions")
subdirs("lib-preferences")
subdirs("lib-math")
subdirs("lib-files")
subdirs("lib-ipc")
subdirs("lib-registries")
subdirs("lib-xml")
subdirs("lib-audio-devices")
subdirs("lib-project")
subdirs("lib-screen-geometry")
subdirs("lib-project-rate")
subdirs("lib-ffmpeg-support")
subdirs("lib-theme")
subdirs("image-compiler")
subdirs("lib-theme-resources")
subdirs("lib-track")
subdirs("lib-transactions")
subdirs("lib-sample-track")
subdirs("lib-module-manager")
subdirs("lib-project-history")
subdirs("lib-graphics")
subdirs("lib-audio-graph")
subdirs("lib-tags")
subdirs("lib-realtime-effects")
subdirs("lib-audio-io")
subdirs("lib-wave-track")
subdirs("lib-track-selection")
subdirs("lib-sentry-reporting")
